name: Deploy Pelican to GitHub Pages

on:
  push:
    branches:
      - main  

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install ghp-import

      - name: Build with Pelican
        run: pelican content -o output -s publishconf.py
        working-directory: projects/tech


      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        working-directory: projects/tech
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./output
