name: Deploy Pelican to GitHub Pages

on:
  push:
    branches:
      - main  # Set the branch to your default branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'  # Set the Python version as per your project

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pelican ghp-import  # Add other dependencies if needed

      - name: Build with Pelican
        run: |
          pelican content -o output -s pelicanconf.py  # Replace with your Pelican build command

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./output  # Set the path to your generated output
